apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: {{ .Values.namespace }}
  labels:
    app: products-service
    chart: {{ .Chart.Name }}
spec:
  selector:
    app: products-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
